### ISSUE TITLE
jqgrid_for_rails and Rails 3.1?

### ISSUE THREAD

**Issue by StefanHelber** [Juanmcuello/jqgrid_for_rails#2]
Hi,

I have tried to emulate the jqgrid_for_rails_example in Rails 3.1.1, using the "will_paginate" gem version 3.0.2. When I try to access "localhost:3000/invoices", I get 

Routing Error

uninitialized constant InvoicesHelper::JqgridsHelper

Is there a way to get this to work under Rails 3.1?

Many thanks for any hints
Stefan

**Comment by Juanmcuello** [comment]
Hi Stefan,

I updated the sample application to make it work with Rails 3.2.0.

I think you shouldn't have any problem with rails 3.1, just change the version in the Gemfile and run bundle install.

Please, give it a try.

**Comment by StefanHelber** [comment]
Hi Juan,

Thanks for the reply. I just installed the sample application under Rails 3.2.0. The grid shows up, I can sort and navigate in the grid (great!!), but when I try to modify (edit) the amount for any selected, I get the following error message:

error Status: 'Not Found '. Error code: 404

The same message comes when I try to add a new record or to delete one. 

I also tried to get the thing to work under Rails 3.1.1 (as you suggested), by changing the Rails version in the Gemfile. However, there are dependencies with 

gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '~> 3.2.1'

which require railties, and I don't really understand these dependencies enough to get the thing to work under Rails 3.1.1, so an additional hint would be nice. 

Under Rails 3.0.9, however, everything appears to work well.

If there should be an additional newbie-compatitble documentation somewhere (apart from the Readme file), I would be grateful for a hint.

Thanks a lot!
Stefan

**Comment by Juanmcuello** [comment]
Stefan, I updated the application to support editing the values. But there are some things you have to consider.

Rails is based on RESTful routes but jqgrid isn't, i.e, all the methods that jqgrid requests to the controller are GET or POST. Methods such as PUT or DELETE are never used (at least at the moment I started with jqgrid, maybe now that has changed). So you will have to adapt your controller to support delete or create operations based on the **'oper'** param that jqgrid sends.

About Rails 3.1, it should work if you change your Gemfile to something like:

``` ruby
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end
```

Sorry, but there is no documentation other than the README. Also take into account that I wrote the plugin a while ago, and there are things that could have been done better.

**Comment by StefanHelber** [comment]
Thanks Juan, that helped. Using "bundle update" I was also able to get it to run under Rails 3.1.1. Again, thanks a lot!

Kind regards
Stefan

**Comment by hvillero** [comment]
Hi Juan

Great Job!!  thank you, I got the rails 3.2 sample working well, but the search is not working, how do you implement search and filters? Thank you for your help

**Comment by Juanmcuello** [comment]
Hi Hugo, 

I'll be on holiday for a few days, I'll back to you next week.

**Comment by hvillero** [comment]
Thank you Juan, I will really appreciate any idea just a bit piece of code will help thx
