### ISSUE TITLE
Accessing row object in formatting proc

### ISSUE THREAD

**Issue by RajRoR** [Juanmcuello/jqgrid_for_rails#5]
There should be the way to access other attributes (columns) in formatting proc.

For Ex: If I have 3 columns namely A, B and C. I want to show "#{A} #{B}" under a column. How to do so?
We can do it in jqgrid: http://jsfiddle.net/fbfcn/5yqRn/13/

**Comment by Juanmcuello** [comment]
I think you could do something like this:

``` ruby
 grid = [{
    # some attributes

    :colNames => ['sno', 'order', 'location'],
    :colModel  => col_model_for_jqgrid(['sno', 'order', 'location'],
        {:formatter => {:location => 'myFormatter'.to_json_var}}) ,

    # More attributes
}]
```

And the just define your `myFormatter` js function somewhere.

Take a look at [here](https://github.com/Juanmcuello/jqgrid_for_rails/blob/master/lib/app/helpers/jqgrids_helper.rb#L144).

**Comment by RajRoR** [comment]
But how rails will know this (myFormatter) is js function and can call it in this code?

```
undefined local variable or method `myFormatter' for #<#<Class:0xb4eefc0>:0xaec7110>
```

**Comment by Juanmcuello** [comment]
Sorry, I forgot to quote the function `myFormatter`. I already fixed it. 

`myformatter` should be a js function defined somewhere.

I updated the [jqgrid_for_rails_example](https://github.com/Juanmcuello/jqgrid_for_rails_example) to show a formatter example.

**Comment by RajRoR** [comment]
Thanks Juanmcuello. It works
