### ISSUE TITLE
includes or joins

### ISSUE THREAD

**Issue by ghost** [Juanmcuello/jqgrid_for_rails#6]
I'm using a controller like so:

@columns = ['invid', 'invdate', 'sometable.name']
@invoices = Invoice.includes(:sometable).paginate(:page => params[:page], :per_page => params[:rows])

```
respond_to do |format|
  format.html # show.html.erb
  format.json {render :json => json_for_jqgrid(@invoices, @columns) }
end
```

The problem is reading the sometable elements (columns). How can I do this? 
I guess json_for_jqgrid is not currently reading joined models.

I know this is not a recent project of yours but I would appreciate hugely the help. This gem eased up this jqgrid for rails greatly.

**Comment by Juanmcuello** [comment]
I updated master branch to take into account these cases.

Say you have a parent object that has_one child. Now you can do something like:

``` ruby
@parent = Parent.first
json_for_jqgrid(@parent, ['name', 'description', 'child.name']) }
```

I didn't have the time to test it very well, please let me know if this works for you and I'll release a new version of the gem.

**Comment by ghost** [comment]
Yes, worked like a charm. The problem now is sorting by this 'child.name'

**Comment by Juanmcuello** [comment]
I'll try to take a look during the weekend. Anyway, I would accept a pull request if you know how to fix it.

**Comment by ghost** [comment]
No bug actually (in this sorting issue). Although in the controller I call

`Invoice.includes(:sometable).paginate(:page => params[:page], :per_page => params[:rows])`

the column header model in javascript has to have the name in plural (like the model), this is

`jQuery("#tableJqList").jqGrid({
        url:'/tables/getData',
        datatype: "json",
        colNames:['name'],
        colModel:[
            { name:'sometables.name', index:'sometables.name' }, (...)`

Thanks a lot for the help, I'll be waiting for the gem release.

**Comment by Juanmcuello** [comment]
Released!
