### ISSUE TITLE
JQgrid not coming on the browser at all

### ISSUE THREAD

**Issue by JagannathLenka** [Juanmcuello/jqgrid_for_rails#7]
Hi,

I am newbie to JQgrid and rails. I tried to clone your example and run it, it works like a charm. I want to replicate this functionality in another project and follow exactly the way you have mentioned in the tutorial. But I am not seeing the grids and in the view source, I dont see even the JQgrid javascripts are coming out. I dont see any errors in the log.
This is what I did.
1. Created a new projects using "rails new JQGrid"
2. Added the followings to Gemfile
gem 'jqgrid_for_rails', git: 'git://github.com/Juanmcuello/jqgrid_for_rails.git'
gem 'will_paginate'
3. Created a controller invoices using "rails generate controller invoices"
4. Created a model invoice
5. Copied the controller code from your tutorial to "invoices_controller"
6. Copied the helper code to "invoices_helper"
7. Copied the views code "index.html.erb"
8. updated the routes.rb accordingly
9.Then I started server

But on the browser was empty and when I checked the source, it was blank. Can you please let me know if I am missing anything

**Comment by Juanmcuello** [comment]
Ensure you are including jqgrid and jquery-ui javascript files. Check in your js console if you are getting any error. If you check the page source it shouldn't be blank. Check the rails console to see if there is any error there. Remember to create 'invoices' table and add some data there.
