### ISSUE TITLE
Compatible with rails 4.2?

### ISSUE THREAD

**Issue by doofpot** [Juanmcuello/jqgrid_for_rails#9]
Hello Juanmcuello,

I looked into your gem and I'm running into some problems with rails 4.2 Everything works fine, except for the to_json_var hook.

Do you have a more recent version available?

Regards,

Sander

**Comment by Juanmcuello** [comment]
Hello Sander,

Sorry, this project is not currently maintained :( 
It's been a long time since the last commit and I don't use Rails anymore. I'll update the Readme file to clarify this.

Sorry and good luck finding an alternative.

**Comment by doofpot** [comment]
Ok, thanks
